### PR TITLE
Profile page added 

### PR DESCRIPTION
**Pull request by Pranav322**
Added a profile page when clicked on avatar in navbar , it has all the necessary information like name email phone number and some miscellaneous info too which can be removed if not needed

### CODE REVIEW

**Review by avishek999 — APPROVED** [review]
ok

**Comment by Shubhamrawat5** [comment]
Please remove the nonFound file from this PR. Also add the link from the nav bar profile icon

**Comment by Pranav322** [comment]
dev had so many new changes so closing this . Will be creating new branch and then send pr again

**Comment by Pranav322** [comment]
dev had so many new changes so closing this . Will be creating new branch and then send pr again

**Pull request closed without merging**
