### PR TITLE
 dummy data added

### PR DESCRIPTION
**Pull request by Raja-Debnath**
dummy data is created check if changes needed

### CODE REVIEW

**Comment by Shubhamrawat5** [comment]
Please change the folder name to "data" and put it inside the src folder

**Comment by Shubhamrawat5** [comment]
json_dummyData - Please remove the old folder

**Comment by Raja-Debnath** [comment]
@Shubhamrawat5 my bad , removed old files

**Comment by ni3mumbaikar** [comment]
https://github.com/PVX-COMMUNITY/admin-dashboard/pull/14

**Pull request closed without merging**
